### ISSUE TITLE
Camera dimensions is not always going to the correct spot on specific android devices (fully kiosk browser)

### ISSUE THREAD

**Issue by borgqueenx** [dermotduffy/advanced-camera-card#2223]
i have the dimensions of the card on, to put the card on a specific portion of the camera. However this is not always working. quite some times when i reload the screen, the camera **IS** listening to the aspect ratio and zoom, but is not panning left/right or up/down to go to the spot i want. It is always working on my desktop windows and linux machines. I also tried the same on the home assistant companion app and see the same issue. Both use webview in android, so maybe it's related to that. it's using the latest though, from the chrome browser.
Due to it being a tablet with limited functionality, it's not simply possible to check debugging...So my question is to perhaps make the moving of the camera a bit more aggresive or robust. Because even on these devices....sometimes it DOES work. I cant reproduce why it works (very few) times.

Code of the card:

```
type: custom:advanced-camera-card
cameras:
  - camera_entity: camera.garden_and_terrace
    live_provider: webrtc-card
    image:
      mode: camera
    go2rtc:
      modes:
        - webrtc
    webrtc_card:
      url: >-
        rtsp://xxxx:xxxx@192.168.1.129:554/Streaming/Channels/102#backchannel=0
    dimensions:
      layout:
        zoom: 2.6
        pan:
          x: 0
          "y": 45
        position:
          x: 50
          "y": 50
        view_box:
          left: 50
          top: 50
          bottom: 50
      aspect_ratio: "22:14"
performance:
  features:
    media_chunk_size: 2
    animated_progress_indicator: false
dimensions: {}
menu:
  style: hidden
  buttons:
    iris:
      enabled: false
    recordings:
      enabled: false
    clips:
      enabled: false
live:
  preload: true

```

Thanks for reading!

**Comment by dermotduffy** [comment]
@borgqueenx How reproducible is this for you? I might have an idea for a fix, but as I can't reproduce the problem I'm hoping you can ...

**Comment by borgqueenx** [comment]
> [@borgqueenx](https://github.com/borgqueenx) How reproducible is this for you? I might have an idea for a fix, but as I can't reproduce the problem I'm hoping you can ...

I can reproduce this without much effort, but i cant tell you what steps to take to make it happen. My guess is that the old slow hardware causes this at random times. If its too busy it will skip moving to the correct art of the camera and will not repeat. Thats why i was hoping it could be made more aggresive/robust. Perhaps a check if it moved, and if not, repeat the command to move to that area.

**Comment by dermotduffy** [comment]
> I can reproduce this without much effort, but i cant tell you what steps to take to make it happen. My guess is that the old slow hardware causes this at random times. If its too busy it will skip moving to the correct art of the camera and will not repeat. Thats why i was hoping it could be made more aggresive/robust. Perhaps a check if it moved, and if not, repeat the command to move to that area.

I too am assuming it's related to slow hardware. I am not such a fan of the "try and if it didn't work try again" approach, as it should work the first time -- adding code like that is debt that needs to hang around forever.

I've committed an experimental "fix", if you can reproduce without much effort, would you mind trying and see if this helps? Make sure you're on at least [v7.24.1](https://github.com/dermotduffy/advanced-camera-card/releases/tag/v7.24.1) and you may need to clear your caches if you don't see that version number momentarily appear on the card when you reload your dashboard.

**Comment by borgqueenx** [comment]
Unfortunately its not solved yet. I have the feeling its more robust though, i also restarted the browser many times on purpose. Sometimes it still shows the center of the camera instead of moving to the correct position. If you have a idea how i can find out why, i'm all ears as well...

**Comment by borgqueenx** [comment]
anything i can try to solve this? i upgraded to RC-4 and the issue remains. most of the time it loads the correct spot, but 1 out of 3 times approximately, it stays to the center of the image. if i load the same dashboard on any other faster device, it always goes to the correct spot.
Perhaps some kind of race condition. that it gives up after loading took a bit longer.

Or perhaps there is a way to force cut part of the camera away? so it HAS to display the part i want?
